#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2018 Ryan Collins <rlcollins@g.harvard.edu>
# Distributed under terms of the MIT license.

"""
Apply batch effect labels to VCF from Talkowski SV pipeline
"""


import argparse
import sys
import pysam
import csv


def reclassify_record(record, reclass, plus_samples):
    if reclass == 'PCRPLUS_ENRICHED':
        record.filter.add('PCRPLUS_ENRICHED')
        for samp in record.samples:
            if samp not in plus_samples:
                record.samples[samp]['GT'] = (None, None)

    elif reclass == 'PCRPLUS_DEPLETED':
        if 'PCRPLUS_DEPLETED' not in record.info.keys():
            record.info.keys().append('PCRPLUS_DEPLETED')
        record.info['PCRPLUS_DEPLETED'] = True
        for samp in record.samples:
            if samp in plus_samples:
                record.samples[samp]['GT'] = (None, None)

    elif reclass == 'VARIABLE_ACROSS_BATCHES':
        record.filter.add('VARIABLE_ACROSS_BATCHES')

    return record


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('vcf', help='Input vcf (supports "stdin").')
    parser.add_argument('reclassifications', help='Tab-delimited reclassification' + 
                        ' table generated by make_batch_effect_reclassification_table.R.')
    parser.add_argument('PCRPLUS_samples', help='List of PCRPLUS sample IDs.')
    parser.add_argument('fout', help='Output file (supports "stdout").')


    args = parser.parse_args()

    #Open connection to input VCF
    if args.vcf in '- stdin'.split():
        vcf = pysam.VariantFile(sys.stdin) 
    else:
        vcf = pysam.VariantFile(args.vcf)

    #Add new FILTER lines to VCF header
    NEW_FILTERS = ['##FILTER=<ID=PCRPLUS_ENRICHED,Description="Site enriched for ' + 
                   'non-reference genotypes among PCR+ samples. Likely reflects ' + 
                   'technical batch effects. All PCR- samples have been assigned ' +
                   'null GTs for these sites.>"',
                   '##FILTER=<ID=VARIABLE_ACROSS_BATCHES,Description="Site appears ' + 
                   'at variable frequencies across batches. Likely reflects technical ' + 
                   'batch effects.>']
    header = vcf.header
    for filt in NEW_FILTERS:
        header.add_line(filt)

    #Add new INFO lines to VCF header
    NEW_INFOS = ['##INFO=<ID=PCRPLUS_DEPLETED,Number=0,Type=Flag,Description=' + 
                 '"Site depleted for non-reference genotypes among PCR+ samples. ' +
                 'Likely reflects technical batch effects. All PCR+ samples have ' + 
                 'been assigned null GTs for these sites.">']
    for info in NEW_INFOS:
        header.add_line(info)

    #Read reclassification table
    reclass_table = {}
    with open(args.reclassifications) as rct:
        reader = csv.reader(rct, delimiter = '\t')
        for VID, assignment in reader:
            if VID not in reclass_table.keys():
                reclass_table[VID] = assignment
    rct.close()

    #Read list of PCR+ samples
    f_plus_samples = open(args.PCRPLUS_samples, 'r')
    plus_samples = f_plus_samples.read().splitlines()
    f_plus_samples.close()

    #Open connection to output VCF
    if args.fout in '- stdout'.split():
        fout = pysam.VariantFile(sys.stdout, 'w', header=vcf.header)
    else:
        fout = pysam.VariantFile(args.fout, 'w', header=vcf.header)

    #Iterate over VCF and process records accordingly
    NULL_GTs = [(0, 0), (None, None), (0, ), (None, ), (None, 2)]
    for record in vcf:
        reclass = reclass_table.get(record.id, None)
        if reclass is None:
            fout.write(record)
        else:
            newrecord = reclassify_record(record, reclass, plus_samples)
            #Only write modified records to file if at least one non-ref allele is retained
            for s in vcf.header.samples:
                if newrecord.samples[s]['GT'] not in NULL_GTs:
                    fout.write(newrecord)
                    break

    fout.close()


if __name__ == '__main__':
    main()
